### ISSUE TITLE
How to escape special characters in text

### ISSUE THREAD

**Issue by tex0l** [hikerpig/pintora#213]
Sometimes I need to use special characters such as `':'`, `'['`, `']'` or wrapping text with quotes, Pintora throws a syntax error. For example:

```
componentDiagram
  [Triggering a syntax error with an escaped colon:]
```
triggers an error

I tried escaping the characters with a single `\` a double `\\`, or wrapping the whole text with quotes.

The only way I managed to make it work is by using HTML entities, but it only works when using SVG.

Is there a way to escape text?

**Comment by hikerpig** [comment]
Since the syntax is quite different among diagrams, there is no simple common escape syntax for all.
In your case of componentDiagram, I'd prefer `[] "Triggering a syntax error with an escaped colon:" as comp` similar to the interface. This has not been implemented yet, though.
And in other diagrams, if the same question is raised, I'd also prefer text wrapped inside double quotes.

**Comment by hikerpig** [comment]
@tex0l Not yet, but I will try to do it.

**Comment by hikerpig** [comment]
Start from v0.6.5 , we can escape double quote char inside quotes.

```pintora
componentDiagram
  component "Escape string example \"here\" " as comp
```
