### ISSUE TITLE
electron standalone version

### ISSUE THREAD

**Issue by kaikaiiiiiii** [hikerpig/pintora#24]
Save and open local files.

any plan?

**Comment by hikerpig** [comment]
Nice suggestion!
Though I prefer PWA since it's lightweight and saves me the burden of setting another repo.
It is also capable of some basic file system operations - according to [one blog of excalidraw](https://blog.excalidraw.com/deprecating-excalidraw-electron/) .
I will consider this after I finish the Gantt Diagram.

**Comment by kaikaiiiiiii** [comment]
Well, the internet never promised she wouldn't leave from you.🙁

**Comment by hikerpig** [comment]
@kaikaiiiiiii What specific features are you expecting ?
1. Standalone , this is already done as the live-editor is a PWA and can be added as a standlone application
2. Edit and preview when offline,  same as the above one
3. Filesystem asccess,  a crude version https://github.com/hikerpig/pintora/pull/29 , you can try this on the Vercel preview
4. File extension asscioation ? Asscioate `.pintora` extension with the application?   I'm still trying to work this out with PWA

Anything else in mind?

**Comment by kaikaiiiiiii** [comment]
good enough,

maybe "drop file to window to open" is convenient, but it's not a must.

**Comment by hikerpig** [comment]
> good enough,
> 
> maybe "drop file to window to open" is convenient, but it's not a must.

This could be done in this week. ✌️

**Comment by hikerpig** [comment]
"drop file to window to open"  has been deployed just now .
